### ISSUE TITLE
Design the Database Schema

### ISSUE THREAD

**Issue by mehalyna** [Project-Stage-Academy/UA-1155-bravo#1]
**Objective**: To create a well-structured database schema that efficiently supports the application's data requirements.

**Sub-Tasks**:
1. **Identify Entities and Relationships**:
   - Analyze the project requirements to identify key entities such as startups, investors, profiles, projects, messages, etc.
   - Determine the relationships between these entities (one-to-many, many-to-many, etc.).

2. **Define Entity Attributes**:
   - List down the attributes for each entity, like startup name, investor details, project descriptions, contact information, etc.

3. **Create ER Diagrams**:
   - Use a database modeling tool to create Entity-Relationship (ER) diagrams representing the structure of the database.

4. **Normalize Database**:
   - Ensure the database design adheres to normalization rules to reduce redundancy and improve data integrity.

5. **Review and Iterate**:
   - Review the schema with the team and iterate based on feedback.

**Comment by oleksandr-liashenko** [comment]
1st stage of DB Schema made on dbdesigner

![Image](https://github.com/Project-Stage-Academy/UA-1155-bravo/assets/102855650/80b3fb02-94c8-4227-9121-a4b4b9650b40)

**Comment by Andrewakiv** [comment]
ER Diagram

![Image](https://github.com/Project-Stage-Academy/UA-1155-bravo/assets/98863447/ef7df655-4caf-4726-92f4-d059e2240ff8)

**Comment by oleksandr-liashenko** [comment]
DB Schema made on dbdesigner, 1 stage finished

![Image](https://github.com/Project-Stage-Academy/UA-1155-bravo/assets/102855650/11e099cf-4fea-4d42-ae1f-8cfea7ff93c1)
